# Generated by Django 6.0.3 on 2026-03-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('job_number', models.CharField(help_text='Format: 111XXXXXXX for EMEA, 222XXXXXXX for APAC, etc.', max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(choices=[('EMEA', 'EMEA'), ('APAC', 'APAC'), ('NA', 'NA'), ('LATAM', 'LATAM')], max_length=10)),
                ('project_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING'), ('ONHOLD', 'ONHOLD'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_hours', models.PositiveIntegerField(default=0)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('assigned_employees', models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
