# Generated by Django 6.0.3 on 2026-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for one hour of work on this project', max_digits=10),
        ),
    ]
