# Generated by Django 6.0.3 on 2026-03-21 18:46

import clients.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[clients.validators.PhoneNumberValidator(), django.core.validators.MinLengthValidator(7, 'The phone number is too short!')])),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
